#!/usr/bin/python3

import wiringpi as pi
import time
import hssr04

LED_PIN = 22
TRIG_PIN = 23
ECHO_PIN = 24

pi.wiringPiSetupGpio()
pi.pinMode( LED_PIN , pi.OUTPUT)
us_dev = hssr04.hssr04(TRIG_PIN , ECHO_PIN)

while True:
    distance = us_dev.read_distance( )
    print( "Distance:",distance,"cm")
    if distance <= 10:
        i = 0
        while i <= 5:
            i += 1
            pi.digitalWrite( LED_PIN , pi.HIGH )
            time.sleep(1)
            pi.digitalWrite( LED_PIN , pi.LOW )
            time.sleep(1)
    else:
        pi.digitalWrite( LED_PIN , pi.LOW )
    time.sleep(1)
